### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Prixix** [Prixix/DasteBin#1]
```
paul@kvm-8c-20gb:~/DasteBin$ yarn start
yarn run v1.22.17
$ node server.js
Swarm listening on /ip4/127.0.0.1/tcp/4002/p2p/12D3KooWRiPp2s6rDnrJ7ppxZxH25oKqE5C24fTpromtZMsspGhn
Swarm listening on /ip4/185.117.0.57/tcp/4002/p2p/12D3KooWRiPp2s6rDnrJ7ppxZxH25oKqE5C24fTpromtZMsspGhn
Swarm listening on /ip4/10.8.0.1/tcp/4002/p2p/12D3KooWRiPp2s6rDnrJ7ppxZxH25oKqE5C24fTpromtZMsspGhn
Swarm listening on /ip4/127.0.0.1/tcp/4003/ws/p2p/12D3KooWRiPp2s6rDnrJ7ppxZxH25oKqE5C24fTpromtZMsspGhn
Server started on port 3000
/home/paul/DasteBin/node_modules/multiformats/cjs/src/cid.js:235
        throw Error('To parse non base32 or base58btc encoded CID multibase decoder must be provided');
              ^

Error: To parse non base32 or base58btc encoded CID multibase decoder must be provided
    at parseCIDtoBytes (/home/paul/DasteBin/node_modules/multiformats/cjs/src/cid.js:235:15)
    at Function.parse (/home/paul/DasteBin/node_modules/multiformats/cjs/src/cid.js:204:29)
    at cat (/home/paul/DasteBin/node_modules/ipfs-core/cjs/src/components/cat.js:15:23)
    at cat.next (<anonymous>)
    at getCode (/home/paul/DasteBin/server.js:90:22)
    at async /home/paul/DasteBin/server.js:62:16
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Prixix** [comment]
Fixed in 4ce6c3f74517de9204e695d8501a207a013af24e
